// each route must be 'required' into the root index.js
const mongoose = require('mongoose');
const requireLogin = require('../middlewares/requireLogin');
const requireCredits = require('../middlewares/requireCredits');

// this is how we include a model to avoid issues with testing frameworks
// alternatively we could just require the file
// we can use this model class to create an instance of a survey
const Survey = mongoose.model('surveys');

module.exports = app => {
	// the req.body will contain the survey content
	app.post('/api/surveys', requireLogin, requireCredits, (req, res) => {
		const { title, subject, body, recipients } = req.body;
		// lowercase 's' to indicate we're creating an instance of 'Survey'
		const survey = new Survey({
			title,
			subject,
			body,
			// array of strings transformed into an array of objects
			// very much condensed conde
			// same as .map(email => { return { email: email }} )
			recipients: recipients.split(',').map(email => ({ email: email.trim() })),
			// id generated by mongoose model
			_user: req.user.id,
			dateSent: Date.now()
		});
	});
};
